export const Icons = {
  avatarAdd: require("../../../assets/images/graphics/superhero/add avatar.png"),
  loadingCharacter: require("../../../assets/images/graphics/animals/capybara loading.png"),
  achievement: require("../../../assets/images/graphics/animals/achievement.png"),
  addition: require("../../../assets/images/graphics/animals/addition.png"),
  avatarFemale: require("../../../assets/images/graphics/animals/avatar female.png"),
  avatarMale: require("../../../assets/images/graphics/animals/avatar male.png"),
  badge: require("../../../assets/images/graphics/animals/badge.png"),
  characterWithBird: require("../../../assets/images/graphics/animals/capybara and bird.png"),
  characterEating: require("../../../assets/images/graphics/animals/capybara holding chicken thigh.png"),
  characterHeart: require("../../../assets/images/graphics/animals/capybara holding heart.png"),
  characterLamp: require("../../../assets/images/graphics/animals/capybara holding oil lamp.png"),
  characterSandwich: require("../../../assets/images/graphics/animals/capybara holding sandwich.png"),
  characterFootball: require("../../../assets/images/graphics/animals/capybara soccer.png"),
  contact: require("../../../assets/images/graphics/animals/contact.png"),
  themeDark: require("../../../assets/images/graphics/animals/dark.png"),
  divisionIcon: require("../../../assets/images/graphics/animals/div.png"),
  division: require("../../../assets/images/graphics/animals/division.png"),
  num8: require("../../../assets/images/graphics/animals/eight.png"),
  languageEnglish: require("../../../assets/images/graphics/animals/english.png"),
  equalMark: require("../../../assets/images/graphics/animals/equal mark.png"),
  exercise: require("../../../assets/images/graphics/animals/exercise.png"),
  num5: require("../../../assets/images/graphics/animals/five.png"),
  num4: require("../../../assets/images/graphics/animals/four.png"),
  game: require("../../../assets/images/graphics/animals/game.png"),
  lesson: require("../../../assets/images/graphics/animals/lesson.png"),
  themeLight: require("../../../assets/images/graphics/animals/light.png"),
  logoDark: require("../../../assets/images/graphics/animals/logo dark.png"),
  logoLight: require("../../../assets/images/graphics/animals/logo light.png"),
  minus: require("../../../assets/images/graphics/animals/minus.png"),
  multiplicationIcon: require("../../../assets/images/graphics/animals/multip.png"),
  multiplicationTables: require("../../../assets/images/graphics/animals/multiplication tables.png"),
  multiplication: require("../../../assets/images/graphics/animals/multiplication.png"),
  num9: require("../../../assets/images/graphics/animals/nine.png"),
  notification: require("../../../assets/images/graphics/animals/notification.png"),
  num1: require("../../../assets/images/graphics/animals/one.png"),
  plus: require("../../../assets/images/graphics/animals/plus.png"),
  point: require("../../../assets/images/graphics/animals/point.png"),
  profile: require("../../../assets/images/graphics/animals/profile.png"),
  testProgress: require("../../../assets/images/graphics/animals/progress test.png"),
  questionMark: require("../../../assets/images/graphics/animals/question mark.png"),
  question: require("../../../assets/images/graphics/animals/question.png"),
  rank: require("../../../assets/images/graphics/animals/rank.png"),
  rewardAlt: require("../../../assets/images/graphics/animals/reward (2).png"),
  reward: require("../../../assets/images/graphics/animals/reward.png"),
  setting: require("../../../assets/images/graphics/animals/setting.png"),
  num7: require("../../../assets/images/graphics/animals/seven.png"),
  num6: require("../../../assets/images/graphics/animals/six.png"),
  soundOff: require("../../../assets/images/graphics/animals/sound off.png"),
  soundOn: require("../../../assets/images/graphics/animals/sound on.png"),
  subtraction: require("../../../assets/images/graphics/animals/subtraction.png"),
  target: require("../../../assets/images/graphics/animals/target.png"),
  testLevel: require("../../../assets/images/graphics/animals/test level.png"),
  test: require("../../../assets/images/graphics/animals/test.png"),
  num3: require("../../../assets/images/graphics/animals/three.png"),
  timeAlt: require("../../../assets/images/graphics/animals/time (2).png"),
  time: require("../../../assets/images/graphics/animals/time.png"),
  top1: require("../../../assets/images/graphics/animals/top 1.png"),
  top2: require("../../../assets/images/graphics/animals/top 2.png"),
  top3: require("../../../assets/images/graphics/animals/top 3.png"),
  top: require("../../../assets/images/graphics/animals/top.png"),
  languageVietnamese: require("../../../assets/images/graphics/animals/vietnamese.png"),
  num0: require("../../../assets/images/graphics/animals/zero.png"),
  back: require("../../../assets/images/graphics/animals/back.png"),
  graphic: require("../../../assets/images/graphics/animals/capybara.png"),
  capybaraloading: require("../../../assets/images/graphics/animals/capybara loading.png"),
  question1: require("../../../assets/images/graphics/questions/1.png"),
  line: require("../../../assets/images/graphics/questions/line.png"),
  multiplication2: require("../../../assets/images/graphics/animals/multiplication2.png"),
  multiplication3: require("../../../assets/images/graphics/animals/multiplication3.png"),
  multiplication4: require("../../../assets/images/graphics/animals/multiplication4.png"),
  multiplication5: require("../../../assets/images/graphics/animals/multiplication5.png"),
  multiplication6: require("../../../assets/images/graphics/animals/multiplication6.png"),
  multiplication7: require("../../../assets/images/graphics/animals/multiplication7.png"),
  multiplication8: require("../../../assets/images/graphics/animals/multiplication8.png"),
  multiplication9: require("../../../assets/images/graphics/animals/multiplication9.png"),
  statistic: require("../../../assets/images/graphics/animals/statistics.png"),
  goal: require("../../../assets/images/graphics/animals/goal.png"),
  privacy: require("../../../assets/images/graphics/animals/privacy.png"),
  changeemail: require("../../../assets/images/graphics/animals/change emial.png"),
  changephone: require("../../../assets/images/graphics/animals/change phone.png"),
  changepin: require("../../../assets/images/graphics/animals/change pin.png"),
  profilepupil: require("../../../assets/images/graphics/capybaras/profile pupil.png"),
  viewprofile: require("../../../assets/images/graphics/animals/view profile.png"),
  ticksuccess: require("../../../assets/images/graphics/capybaras/ticksuccess.png"),
  error: require("../../../assets/images/graphics/capybaras/error.png"),
  confirm: require("../../../assets/images/graphics/capybaras/confirm.png"),
  warning: require("../../../assets/images/graphics/capybaras/warning.png"),
};
export type Theme2Icons = typeof Icons;
