import { StyleSheet } from "react-native";
import { Fonts } from "../../../../constants/Fonts";

export const getStyles = (theme, getBorderBox) =>
  StyleSheet.create({
    container: {
      flex: 1,
      paddingTop: 20,
      backgroundColor: theme.colors.background,
    },
    operatorDisabled: {
      opacity: 0.5, // Example: make disabled buttons look grayed out
      backgroundColor: theme.colors.gray, // Optional: different background
    },
    header: {
      width: "100%",
      height: "18%",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      borderBottomLeftRadius: 50,
      borderBottomRightRadius: 50,
      elevation: 3,
      marginBottom: 20,
    },
    backButton: {
      position: "absolute",
      left: 10,
      backgroundColor: theme.colors.backBackgound,
      marginLeft: 20,
      padding: 8,
      borderRadius: 50,
    },
    backIcon: {
      width: 24,
      height: 24,
    },
    headerText: {
      fontSize: 32,
      fontFamily: Fonts.NUNITO_BOLD,
      color: theme.colors.white,
    },
    stepBox: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
    },
    titleContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
    },
    soundContainer: {
      width: 42,
      alignItems: "center",
      paddingVertical: 5,
      borderRadius: 50,
      elevation: 3,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: theme.colors.white,
    },
    title: {
      fontSize: 18,
      color: theme.colors.black,
      fontWeight: 600,
      marginBottom: 10,
      width: "80%",
    },
    inputBox: {
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: getBorderBox(),
      padding: 10,
      borderRadius: 10,
      width: "40%",
      height: 200,
      textAlign: "center",
      color: theme.colors.black,
      fontFamily: Fonts.NUNITO_MEDIUM,
    },
    numberBoxContainer: {
      flex: 1,
      margin: 10,
    },
    numberContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
    },
    operatorContainer: {
      position: "relative",
      width: "30%",
      height: 120,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: getBorderBox(),
      borderRadius: 10,
      marginBottom: 30,
    },
    operator: {
      fontFamily: Fonts.NUNITO_MEDIUM,
      fontSize: 80,
      color: theme.colors.black,
      fontFamily: Fonts.NUNITO_MEDIUM,
    },
    numbersContainer: {
      width: "30%",
    },
    numberBox: {
      height: 120,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: getBorderBox(),
      borderRadius: 10,
      marginBottom: 30,
    },
    number: {
      fontFamily: Fonts.NUNITO_MEDIUM,
      fontSize: 80,
      color: theme.colors.black,
    },
    lineIconContainer: {
      alignItems: "center",
    },
    lineIcon: { width: "80%", height: 10 },
    resultTextContainer: {
      height: 120,
      width: "60%",
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: getBorderBox(),
      borderRadius: 10,
      marginBottom: 30,
      marginLeft: 80,
      justifyContent: "center",
    },
    resultText: {
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: getBorderBox(),
      fontSize: 80,
      textAlign: "center",
    },
    subText: {
      fontSize: 14,
      color: theme.colors.w,
      fontFamily: Fonts.NUNITO_MEDIUM,
      width: "80%",
      textAlign: "center",
    },
    nextButton: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      paddingVertical: 10,
      borderTopLeftRadius: 50,
      borderTopRightRadius: 50,
    },
    nextText: {
      color: theme.colors.white,
      fontSize: 18,
      fontFamily: Fonts.NUNITO_BOLD,
      textAlign: "center",
    },
    backStepContainer: {
      flexDirection: "row",
    },
    backStepButton: {
      borderRadius: 30,
      margin: 10,
      borderWidth: 1,
      borderColor: theme.colors.white,
      padding: 5,
      elevation: 3,
    },
    numberInputRow: {
      flexDirection: "row",
      justifyContent: "space-around",
      width: "100%",
    },
    placeholderText: {
      position: "absolute",
      top: 75,
      fontSize: 40,
      color: theme.colors.grayLight,
      fontFamily: Fonts.NUNITO_MEDIUM,
    },
    placeholderLeft: { left: 25 },
    placeholderRight: { right: 25 },
    operatorRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    operatorButton: {
      borderRadius: 10,
      marginHorizontal: 5,
      marginBottom: 15,
      width: "20%",
      justifyContent: "center",
      alignItems: "center",
      elevation: 3,
    },
    operatorActive: { backgroundColor: getBorderBox() },
    operatorSymbolContainer: {
      width: 70,
      height: 150,
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
    },
    lockOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.2)",
      borderRadius: 10,
      zIndex: 10,
    },
    operatorInactive: { backgroundColor: theme.colors.grayMedium },
    hiddenButton: {
      opacity: 0, // Làm nút trong suốt nhưng vẫn chiếm chỗ
      pointerEvents: "none", // Vô hiệu hóa tương tác
    },
    hiddenText: {
      color: "transparent", // Làm chữ trong suốt
    },
    operatorSymbol: { fontSize: 100, color: theme.colors.highlightText },
    scrollContainer: { flexGrow: 1, paddingBottom: 40 },
    calText: {
      fontFamily: Fonts.NUNITO_MEDIUM,
      fontSize: 16,
      color: getBorderBox(),
      marginLeft: 20,
    },
    horizontalBox: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 12,
      marginVertical: 20,
    },
    dashedBox: {
      borderWidth: 2,
      borderStyle: "dashed",
      borderColor: getBorderBox(),
      borderRadius: 10,
      paddingVertical: 12,
      paddingHorizontal: 16,
      maxWidth: 130,
      alignItems: "center",
      justifyContent: "center",
    },
    horizontalText: {
      fontSize: 60,
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: theme.colors.black,
      textAlign: "center",
    },
    verticalWrap: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "flex-start",
      gap: 10,
      marginVertical: 20,
    },
    operatorOutside: {
      fontSize: 50,
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: theme.colors.black,
      marginTop: 50,
    },
    verticalBox: {
      gap: 12,
    },
    verticalDashedBox: {
      borderStyle: "dashed",
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "stretch",
      paddingRight: 30,
      minWidth: 60,
    },
    verticalText: {
      fontSize: 40,
      fontFamily: Fonts.NUNITO_MEDIUM,
      color: theme.colors.black,
      textAlign: "right",
    },
  });
