export const Images = {
  avatarAdd: require("../../../assets/images/graphics/superhero/add avatar.png"),
  loadingCharacter: require("../../../assets/images/graphics/superhero/capybara loading.png"),
  achievement: require("../../../assets/images/graphics/superhero/achievement.png"),
  addition: require("../../../assets/images/graphics/superhero/addition.png"),
  avatarFemale: require("../../../assets/images/graphics/superhero/avatar female.png"),
  avatarMale: require("../../../assets/images/graphics/superhero/avatar male.png"),
  badge: require("../../../assets/images/graphics/superhero/badge.png"),
  characterWithBird: require("../../../assets/images/graphics/superhero/capybara and bird.png"),
  characterEating: require("../../../assets/images/graphics/superhero/capybara holding chicken thigh.png"),
  characterHeart: require("../../../assets/images/graphics/superhero/capybara holding heart.png"),
  characterLamp: require("../../../assets/images/graphics/superhero/capybara holding oil lamp.png"),
  characterSandwich: require("../../../assets/images/graphics/superhero/capybara holding sandwich.png"),
  characterFootball: require("../../../assets/images/graphics/superhero/capybara soccer.png"),
  contact: require("../../../assets/images/graphics/superhero/contact.png"),
  themeDark: require("../../../assets/images/graphics/superhero/dark.png"),
  divisionIcon: require("../../../assets/images/graphics/superhero/div.png"),
  division: require("../../../assets/images/graphics/superhero/division.png"),
  num8: require("../../../assets/images/graphics/superhero/eight.png"),
  languageEnglish: require("../../../assets/images/graphics/superhero/english.png"),
  equalMark: require("../../../assets/images/graphics/superhero/equal mark.png"),
  exercise: require("../../../assets/images/graphics/superhero/exercise.png"),
  num5: require("../../../assets/images/graphics/superhero/five.png"),
  num4: require("../../../assets/images/graphics/superhero/four.png"),
  game: require("../../../assets/images/graphics/superhero/game.png"),
  lesson: require("../../../assets/images/graphics/superhero/lesson.png"),
  themeLight: require("../../../assets/images/graphics/superhero/light.png"),
  logoDark: require("../../../assets/images/graphics/superhero/logo dark.png"),
  logoLight: require("../../../assets/images/graphics/superhero/logo light.png"),
  minus: require("../../../assets/images/graphics/superhero/minus.png"),
  multiplicationIcon: require("../../../assets/images/graphics/superhero/multip.png"),
  multiplicationTables: require("../../../assets/images/graphics/superhero/multiplication tables.png"),
  multiplication: require("../../../assets/images/graphics/superhero/multiplication.png"),
  num9: require("../../../assets/images/graphics/superhero/nine.png"),
  notification: require("../../../assets/images/graphics/superhero/notification.png"),
  num1: require("../../../assets/images/graphics/superhero/one.png"),
  plus: require("../../../assets/images/graphics/superhero/plus.png"),
  point: require("../../../assets/images/graphics/superhero/point.png"),
  profile: require("../../../assets/images/graphics/superhero/profile.png"),
  testProgress: require("../../../assets/images/graphics/superhero/progress test.png"),
  questionMark: require("../../../assets/images/graphics/superhero/question mark.png"),
  question: require("../../../assets/images/graphics/superhero/question.png"),
  rank: require("../../../assets/images/graphics/superhero/rank.png"),
  rewardAlt: require("../../../assets/images/graphics/superhero/reward (2).png"),
  reward: require("../../../assets/images/graphics/superhero/reward.png"),
  setting: require("../../../assets/images/graphics/superhero/setting.png"),
  num7: require("../../../assets/images/graphics/superhero/seven.png"),
  num6: require("../../../assets/images/graphics/superhero/six.png"),
  soundOff: require("../../../assets/images/graphics/superhero/sound off.png"),
  soundOn: require("../../../assets/images/graphics/superhero/sound on.png"),
  subtraction: require("../../../assets/images/graphics/superhero/subtraction.png"),
  target: require("../../../assets/images/graphics/superhero/target.png"),
  testLevel: require("../../../assets/images/graphics/superhero/test level.png"),
  test: require("../../../assets/images/graphics/superhero/test.png"),
  num3: require("../../../assets/images/graphics/superhero/three.png"),
  timeAlt: require("../../../assets/images/graphics/superhero/time (3).png"),
  time: require("../../../assets/images/graphics/superhero/time.png"),
  top1: require("../../../assets/images/graphics/superhero/top 1.png"),
  top2: require("../../../assets/images/graphics/superhero/top 2.png"),
  top3: require("../../../assets/images/graphics/superhero/top 3.png"),
  top: require("../../../assets/images/graphics/superhero/top.png"),
  languageVietnamese: require("../../../assets/images/graphics/superhero/vietnamese.png"),
  num0: require("../../../assets/images/graphics/superhero/zero.png"),
  back: require("../../../assets/images/graphics/superhero/back.png"),
  graphic: require("../../../assets/images/graphics/superhero/capybara.png"),
  capybaraloading: require("../../../assets/images/graphics/superhero/capybara loading.png"),
};
export type Theme3Images = typeof Images;
