export const Icons = {
  avatarAdd: require("../../../assets/images/graphics/capybaras/add avatar.png"),
  loadingCharacter: require("../../../assets/images/graphics/capybaras/capybara loading.png"),
  achievement: require("../../../assets/images/graphics/capybaras/achievement.png"),
  addition: require("../../../assets/images/graphics/capybaras/addition.png"),
  avatarFemale: require("../../../assets/images/graphics/capybaras/avatar female.png"),
  avatarMale: require("../../../assets/images/graphics/capybaras/avatar male.png"),
  badge: require("../../../assets/images/graphics/capybaras/badge.png"),
  characterWithBird: require("../../../assets/images/graphics/capybaras/capybara and bird.png"),
  characterEating: require("../../../assets/images/graphics/capybaras/capybara holding chicken thigh.png"),
  characterHeart: require("../../../assets/images/graphics/capybaras/capybara holding heart.png"),
  characterLamp: require("../../../assets/images/graphics/capybaras/capybara holding oil lamp.png"),
  characterSandwich: require("../../../assets/images/graphics/capybaras/capybara holding sandwich.png"),
  characterFootball: require("../../../assets/images/graphics/capybaras/capybara soccer.png"),
  contact: require("../../../assets/images/graphics/capybaras/contact.png"),
  themeDark: require("../../../assets/images/graphics/capybaras/dark.png"),
  divisionIcon: require("../../../assets/images/graphics/capybaras/div.png"),
  division: require("../../../assets/images/graphics/capybaras/division.png"),
  num8: require("../../../assets/images/graphics/capybaras/eight.png"),
  languageEnglish: require("../../../assets/images/graphics/capybaras/english.png"),
  equalMark: require("../../../assets/images/graphics/capybaras/equal mark.png"),
  exercise: require("../../../assets/images/graphics/capybaras/exercise.png"),
  num5: require("../../../assets/images/graphics/capybaras/five.png"),
  num4: require("../../../assets/images/graphics/capybaras/four.png"),
  game: require("../../../assets/images/graphics/capybaras/game.png"),
  lesson: require("../../../assets/images/graphics/capybaras/lesson.png"),
  themeLight: require("../../../assets/images/graphics/capybaras/light.png"),
  logoDark: require("../../../assets/images/graphics/capybaras/logo dark.png"),
  logoLight: require("../../../assets/images/graphics/capybaras/logo light.png"),
  minus: require("../../../assets/images/graphics/capybaras/minus.png"),
  multiplicationIcon: require("../../../assets/images/graphics/capybaras/multip.png"),
  multiplicationTables: require("../../../assets/images/graphics/capybaras/multiplication tables.png"),
  multiplication: require("../../../assets/images/graphics/capybaras/multiplication.png"),
  num9: require("../../../assets/images/graphics/capybaras/nine.png"),
  notification: require("../../../assets/images/graphics/capybaras/notification.png"),
  num1: require("../../../assets/images/graphics/capybaras/one.png"),
  plus: require("../../../assets/images/graphics/capybaras/plus.png"),
  point: require("../../../assets/images/graphics/capybaras/point.png"),
  profile: require("../../../assets/images/graphics/capybaras/profile.png"),
  testProgress: require("../../../assets/images/graphics/capybaras/progress test.png"),
  questionMark: require("../../../assets/images/graphics/capybaras/question mark.png"),
  question: require("../../../assets/images/graphics/capybaras/question.png"),
  rank: require("../../../assets/images/graphics/capybaras/rank.png"),
  rewardAlt: require("../../../assets/images/graphics/capybaras/reward (2).png"),
  reward: require("../../../assets/images/graphics/capybaras/reward.png"),
  setting: require("../../../assets/images/graphics/capybaras/setting.png"),
  num7: require("../../../assets/images/graphics/capybaras/seven.png"),
  num6: require("../../../assets/images/graphics/capybaras/six.png"),
  soundOff: require("../../../assets/images/graphics/capybaras/sound off.png"),
  soundOn: require("../../../assets/images/graphics/capybaras/sound on.png"),
  subtraction: require("../../../assets/images/graphics/capybaras/subtraction.png"),
  target: require("../../../assets/images/graphics/capybaras/target.png"),
  testLevel: require("../../../assets/images/graphics/capybaras/test level.png"),
  test: require("../../../assets/images/graphics/capybaras/test.png"),
  num3: require("../../../assets/images/graphics/capybaras/three.png"),
  timeAlt: require("../../../assets/images/graphics/capybaras/time (2).png"),
  time: require("../../../assets/images/graphics/capybaras/time.png"),
  top1: require("../../../assets/images/graphics/capybaras/top 1.png"),
  top2: require("../../../assets/images/graphics/capybaras/top 2.png"),
  top3: require("../../../assets/images/graphics/capybaras/top 3.png"),
  top: require("../../../assets/images/graphics/capybaras/top.png"),
  languageVietnamese: require("../../../assets/images/graphics/capybaras/vietnamese.png"),
  num0: require("../../../assets/images/graphics/capybaras/zero.png"),
  back: require("../../../assets/images/graphics/capybaras/back.png"),
  graphic: require("../../../assets/images/graphics/capybaras/capybara.png"),
  capybaraloading: require("../../../assets/images/graphics/capybaras/capybara loading.png"),
  question1: require("../../../assets/images/graphics/questions/1.png"),
  line: require("../../../assets/images/graphics/questions/line.png"),
  multiplication2: require("../../../assets/images/graphics/capybaras/multiplication2.png"),
  multiplication3: require("../../../assets/images/graphics/capybaras/multiplication3.png"),
  multiplication4: require("../../../assets/images/graphics/capybaras/multiplication4.png"),
  multiplication5: require("../../../assets/images/graphics/capybaras/multiplication5.png"),
  multiplication6: require("../../../assets/images/graphics/capybaras/multiplication6.png"),
  multiplication7: require("../../../assets/images/graphics/capybaras/multiplication7.png"),
  multiplication8: require("../../../assets/images/graphics/capybaras/multiplication8.png"),
  multiplication9: require("../../../assets/images/graphics/capybaras/multiplication9.png"),
  statistic: require("../../../assets/images/graphics/capybaras/statistics.png"),
  goal: require("../../../assets/images/graphics/capybaras/goal.png"),
  privacy: require("../../../assets/images/graphics/capybaras/privacy.png"),
  changeemail: require("../../../assets/images/graphics/capybaras/change emial.png"),
  changephone: require("../../../assets/images/graphics/capybaras/change phone.png"),
  changepin: require("../../../assets/images/graphics/capybaras/change pin.png"),
  profilepupil: require("../../../assets/images/graphics/capybaras/profile pupil.png"),
  viewprofile: require("../../../assets/images/graphics/capybaras/view profile.png"),
  ticksuccess: require("../../../assets/images/graphics/capybaras/ticksuccess.png"),
  error: require("../../../assets/images/graphics/capybaras/error.png"),
  confirm: require("../../../assets/images/graphics/capybaras/confirm.png"),
  warning: require("../../../assets/images/graphics/capybaras/warning.png"),
};
export type Theme1Icons = typeof Icons;
